### ISSUE TITLE
TypeError: flip() missing 1 required positional argument: 'axis'

### ISSUE THREAD

**Issue by kamalhussain** [nuno-faria/tiler#10]
The tiler.py fails with the following error:

```
Creating tiled image
  0%|                                                                                                | 0/999990 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "tiler.py", line 225, in <module>
  File "tiler.py", line 220, in main
    if __name__ == "__main__":
  File "tiler.py", line 190, in create_tiled_image

  File "tiler.py", line 175, in place_tile
    mask = mask[:img_box.shape[0], :img_box.shape[1]]
TypeError: flip() missing 1 required positional argument: 'axis'
```

**Comment by kamalhussain** [comment]
It works after upgrading Python and other modules.
