### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'astype'

### ISSUE THREAD

**Issue by tianxia0079** [nuno-faria/tiler#14]
$ python tiler.py path/to/image path/to/tiles_folder/
0it [00:00, ?it/s]
Loading tiles
Gettting and processing boxes
Traceback (most recent call last):
  File "tiler.py", line 221, in <module>
    main()
  File "tiler.py", line 215, in main
    boxes, original_res = get_processed_image_boxes(image_path, tiles)
  File "tiler.py", line 149, in get_processed_image_boxes
    img = read_image(image_path)
  File "tiler.py", line 34, in read_image
    img = color_quantization(img.astype('float'), COLOR_DEPTH)
AttributeError: 'NoneType' object has no attribute 'astype'
how to deal  thanks!

**Comment by tianxia0079** [comment]
$ python tiler.py path/to/image/a.png path/to/tiles_folder/
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
Loading tiles
Gettting and processing boxes
Creating tiled image

the first arg must be a image path ,not folder path.
