### ISSUE TITLE
gen_tiles.py fails on certain images 

### ISSUE THREAD

**Issue by patschreiber** [nuno-faria/tiler#17]
Certain images seem to work, but most fail with a very similar message to the example below

All commands run from tiler's root directory (`tiler/`)
Run command with `.jpg` version of image
```bash
python3 gen_tiles.py images/test2/test2.jpg
```

Output
```python
  0%|                                                     | 0/5 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "gen_tiles.py", line 31, in <module>
    new_img = img * [b, g, r, 1]
ValueError: operands could not be broadcast together with shapes (1360,1000,3) (4,) 
```

Convert image to `.png`, run command again
```bash
python3 gen_tiles.py images/test2/test2.png
```

Output: 
```python
Traceback (most recent call last):
  File "gen_tiles.py", line 23, in <module>
    img = img.astype('float')
AttributeError: 'NoneType' object has no attribute 'astype'
```
-------
**System information:**
* `Python 3.7.2`
* `pip 18.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)`
* `Mac OS X 10.14.5`

**Comment by nuno-faria** [comment]
I fixed the problem for the `.jpg` images. Give that a try now.

As for the `.png` one, are you sure `images/test2/test2.png` exists and is a valid image? If so, could you send it?
