### ISSUE TITLE
Conntinually receive IndexError: index 3 is out of bounds for axis 2 with size 3

### ISSUE THREAD

**Issue by alliedcvil** [nuno-faria/tiler#18]
When trying to generate tiles I receive this with a standard image.

Traceback (most recent call last):
  File "tiler.py", line 221, in <module>
    main()
  File "tiler.py", line 216, in main
    img = create_tiled_image(boxes, original_res, render=conf.RENDER)
  File "tiler.py", line 186, in create_tiled_image
    place_tile(img, box)
  File "tiler.py", line 173, in place_tile
    mask = box['tile'][:, :, 3] != 0
IndexError: index 3 is out of bounds for axis 2 with size 3

**Comment by nuno-faria** [comment]
It should be fixed now. Give it a try and let me know.
