### ISSUE TITLE
No module name cv2

### ISSUE THREAD

**Issue by kchar92** [nuno-faria/tiler#23]
Keep getting this error

Traceback (most recent call last):
  File "tiler.py", line 1, in <module>
    import cv2
ImportError: No module named cv2

**Comment by nuno-faria** [comment]
You need to install the dependencies. Using pip: `pip install -r requirements.txt`.

**Comment by kchar92** [comment]
Still getting an error

Traceback (most recent call last):
  File "tiler.py", line 1, in <module>
    import cv2
  File "/usr/local/lib/python3.7/site-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: dlopen(/usr/local/lib/python3.7/site-packages/cv2/cv2.so, 2): Symbol not found: _PyCObject_Type
  Referenced from: /usr/local/lib/python3.7/site-packages/cv2/cv2.so
  Expected in: flat namespace
 in /usr/local/lib/python3.7/site-packages/cv2/cv2.so
