### ISSUE TITLE
"invalid syntax" or "AttributeError: 'Pool' object has no attribute 'starmap'"

### ISSUE THREAD

**Issue by N4n3x** [nuno-faria/tiler#26]
Hi, I can't get your program to work. Indeed, 
if I try 
`D:\Programs\Tiler\tiler-master>python tiler.py images/cake/cake.png tiles/circles/gen_circle_100`

I get the message:
```
Loading tiles
100%|##########| 125/125 [00:02<00:00, 59.44it/s]
Gettting and processing boxes
  0%|          | 0/5 [00:00<?, ?it/s]Traceback (most recent call last):
  File "tiler.py", line 223, in <module>
    main()
  File "tiler.py", line 217, in main
    boxes, original_res = get_processed_image_boxes(image_path, tiles)
  File "tiler.py", line 158, in get_processed_image_boxes
    most_similar_tiles = pool.starmap(most_similar_tile, zip(modes, [ts for x in range(len(modes))]))
AttributeError: 'Pool' object has no attribute 'starmap'
  0%|          | 0/5 [00:17<?, ?it/s]
```

and if i try `D:\Programmes\Tiler\tiler-master>python gen_tiles.py images/cake/cake.png`
i get 
```
File "gen_tiles.py", line 45
    f'{out_folder}/{img_name}_{round(r,1)}_{round(g,1)}_{round(b,1)}_r{rotation}.{ext}',
                                                                                      ^
SyntaxError: invalid syntax
```

It's a bug or I didn't understand the instructions?

**Comment by nuno-faria** [comment]
You need Python 3. #19
