### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Orion545** [nuno-faria/tiler#27]
Get this when I tried to run my first time tiler

Error message:

```
Loading tiles
  0%|                                                                                                                                                 | 0/13 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "tiler.py", line 223, in <module>
    main()
  File "tiler.py", line 216, in main
    tiles = load_tiles(tiles_paths)
  File "tiler.py", line 85, in load_tiles
    tile = read_image(os.path.join(path, tile_name))
  File "tiler.py", line 34, in read_image
    if img.shape[2] == 3:
AttributeError: 'NoneType' object has no attribute 'shape'
```

My settings are all correct, they look like this:

```python3
# GEN TILES CONFS

# number of divisions per color (R, G and B)
# DEPTH = 4 -> 4 * 4 * 4 = 64 colors
DEPTH = 4
# list of rotations, in degrees, to apply over the original image
ROTATIONS = [0]


#############################


# TILER CONFS

# number of colors per image
COLOR_DEPTH = 32
# tiles scales (1 = default resolution)
RESIZING_SCALES = [0.5, 0.4, 0.3, 0.2, 0.1]
# number of pixels shifted to create each box (tuple with (x,y))
# if value is None, shift will be done accordingly to tiles dimensions
PIXEL_SHIFT = (5, 5)
# if tiles can overlap
OVERLAP_TILES = False
# render image as its being built
RENDER = False
# multiprocessing pool size
POOL_SIZE = 8

# out file name
OUT = 'out.png'
# image to tile (ignored if passed as the 1st arg)
IMAGE_TO_TILE = '/home/orion545/Pictures/57570276_p00.jpg'
# folder with tiles (ignored if passed as the 2nd arg)
TILES_FOLDER = '/home/orion545/BT/tiler/'
```

I'm using Python3, all dependencies are correctly installed

**Comment by Orion545** [comment]
problem solved when correctedly manipulated the path to tiles
