### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by LeRegedit** [nuno-faria/tiler#40]
Traceback (most recent call last):
  File "/home/kali/tiler/tiler.py", line 223, in <module>
    main()
  File "/home/kali/tiler/tiler.py", line 217, in main
    boxes, original_res = get_processed_image_boxes(image_path, tiles)
  File "/home/kali/tiler/tiler.py", line 151, in get_processed_image_boxes
    img = read_image(image_path)
  File "/home/kali/tiler/tiler.py", line 34, in read_image
    if img.shape[2] == 3:
IndexError: tuple index out of range

**Comment by nuno-faria** [comment]
Does the path with the tiles only contain images?

**Comment by LeRegedit** [comment]
Fixed: Image was too small (I think).
